FROM jupyter/scipy-notebook:latest

USER root
WORKDIR /tmp

RUN apt-get update && apt-get install -y gnupg curl fonts-ipafont fonts-ipaexfont
# Google Chrome下载
RUN wget https://dl.google.com/linux/linux_signing_key.pub \
 && apt-key add linux_signing_key.pub \
 && echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list \
 && apt-get update \
 && apt-get install -y google-chrome-stable \
 && google-chrome --version

# Chrome Driver下载
RUN CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE` \
 && curl -sS -o /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip \
 && unzip /tmp/chromedriver_linux64.zip \
 && mv chromedriver /usr/local/bin/

## 变换权限到jovyan用户
RUN chown -R jovyan /home/jovyan/.local

USER jovyan
# selenium
RUN pip install selenium
WORKDIR /home/jovyan

COPY cookbook.ipynb /home/jovyan
COPY pictures /home/jovyan/
COPY settings.py /home/jovyan/
COPY Downie.crx /home/jovyan/
COPY scripts /home/jovyan/
COPY md.py /home/jovyan/
COPY root /home/jovyan/